name: React CI with Docker

on:
  push:
    branches: [ "dev" ] # 또는 원하는 브랜치
  pull_request:
    branches: [ "dev" ] # 또는 원하는 브랜치

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # (1) 기본 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mealkeat:frontlatest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mealkeat:frontlatest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
